name: Auto review with reviewdog

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  textlint:
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.3.0
        with:
          reviewdog_version: latest

      - name: Fetch base branch
        run: git fetch origin ${{github.base_ref}} --depth=1

      - name: Run textlint with reviewdog
        run: |
          git diff -z --diff-filter=ACMR --name-only origin/${{github.base_ref}} HEAD \
            | xargs -0 npx --no-install textlint --fix || true

          git diff -z --diff-filter=ACMR --name-only origin/${{github.base_ref}} HEAD \
            | xargs -0 npx --no-install textlint -f checkstyle \
            | reviewdog -f=checkstyle \
              -name=textlint \
              -reporter=github-pr-review \
              -filter-mode=added \
              -fail-on-error=false \
              -level=warning

          TMPFILE=$(mktemp -p ${{runner.temp}})
          git diff > "${TMPFILE}"
          git stash -u && git stash drop || true

          reviewdog \
            -f=diff \
            -f.diff.strip=1 \
            -name=textlint-fix \
            -reporter=github-pr-review \
            -filter-mode=diff_context \
            -level=warning < "${TMPFILE}"
